
(() => {
'use strict';
const $=id=>document.getElementById(id), uid=()=> 'id-'+Math.random().toString(36).slice(2,10), clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const canvas=$('rigCanvas'),ctx=canvas.getContext('2d'),viewport=$('viewport');
const layers=[{id:'background',name:'Background',visible:true,locked:true},{id:'rigging',name:'Rigging',visible:true,locked:false},{id:'performers',name:'Performers',visible:true,locked:false},{id:'equipment',name:'Equipment',visible:true,locked:false},{id:'annotations',name:'Annotations',visible:true,locked:false},{id:'measurements',name:'Measurements',visible:true,locked:false}];
const assets=[
{name:'Telehandler',type:'telehandler',src:'assets/telehandler.webp',w:430,h:260,points:[['Boom tip',.05,.18],['Boom pivot',.54,.39],['Rear anchor',.84,.66],['Front chassis',.45,.82]]},
{name:'Pulley',type:'pulley',src:'assets/pulley.svg',w:90,h:90,points:[['Axle',.5,.55],['Left rope',.05,.55],['Right rope',.95,.55],['Top',.5,.08]]},
{name:'Double pulley',type:'double',src:'assets/double-pulley.svg',w:120,h:90,points:[['Top',.5,.08],['Left rope',.05,.58],['Centre',.5,.58],['Right rope',.95,.58]]},
{name:'Truss',type:'truss',src:'assets/truss.svg',w:280,h:75,points:[['Left',.02,.5],['Centre',.5,.5],['Right',.98,.5]]},
{name:'Performer',type:'performer',src:'assets/performer.svg',w:70,h:155,points:[['Head',.5,.08],['Dorsal',.5,.31],['Ventral',.5,.53],['Left hand',.05,.53],['Right hand',.95,.53],['Feet',.5,.97]]},
{name:'Winch',type:'winch',src:'assets/winch.svg',w:145,h:100,points:[['Line out',.02,.45],['Drum',.5,.6],['Rear',.98,.45]]},
{name:'Anchor',type:'anchor',src:'assets/anchor.svg',w:80,h:100,points:[['Connection',.5,.1]]},
{name:'Shackle',type:'shackle',src:'assets/shackle.svg',w:65,h:85,points:[['Pin',.5,.2],['Bow',.5,.92]]},
{name:'Rope grab',type:'ropegrab',src:'assets/rope-grab.svg',w:65,h:100,points:[['Top',.5,.03],['Bottom',.5,.97],['Attachment',.75,.5]]}
];
const state={projectId:uid(),projectName:'Untitled Project',objects:[],lines:[],background:null,backgroundOpacity:.8,layers:JSON.parse(JSON.stringify(layers)),selectedId:null,tool:'select',perspective:false,zoom:1,history:[],future:[],drawings:[],calendar:[],month:new Date().getMonth(),year:new Date().getFullYear(),harnessNotes:''};
let bgImage=null,drag=null,drawing=null,imageCache=new Map();

function snapshot(){return JSON.stringify({projectId:state.projectId,projectName:state.projectName,objects:state.objects,lines:state.lines,background:state.background,backgroundOpacity:state.backgroundOpacity,layers:state.layers,drawings:state.drawings,calendar:state.calendar,harnessNotes:state.harnessNotes})}
function pushHistory(){state.history.push(snapshot());if(state.history.length>70)state.history.shift();state.future=[];$('saveStatus').textContent='Unsaved';clearTimeout(pushHistory.t);pushHistory.t=setTimeout(saveProject,700)}
function restore(raw){Object.assign(state,JSON.parse(raw));state.selectedId=null;loadBackground();renderAll()}
function projectMap(){try{return JSON.parse(localStorage.getItem('simplerig-pro-projects')||'{}')}catch{return{}}}
function saveProject(){state.projectName=$('projectName').value.trim()||'Untitled Project';state.harnessNotes=$('harnessNotes').value;const ps=projectMap();ps[state.projectId]={id:state.projectId,name:state.projectName,updated:new Date().toISOString(),data:snapshot()};localStorage.setItem('simplerig-pro-projects',JSON.stringify(ps));localStorage.setItem('simplerig-pro-current',state.projectId);$('saveStatus').textContent='Saved locally';renderProjects()}
function loadProject(id){const p=projectMap()[id];if(!p)return;Object.assign(state,JSON.parse(p.data));$('projectName').value=state.projectName;$('harnessNotes').value=state.harnessNotes||'';state.selectedId=null;state.history=[];state.future=[];loadBackground();renderAll();switchView('workspace')}
function newProject(){if(!confirm('Create a new project?'))return;Object.assign(state,{projectId:uid(),projectName:'Untitled Project',objects:[],lines:[],background:null,backgroundOpacity:.8,layers:JSON.parse(JSON.stringify(layers)),selectedId:null,history:[],future:[],drawings:[],calendar:[],harnessNotes:''});$('projectName').value=state.projectName;$('harnessNotes').value='';loadBackground();renderAll();saveProject()}
function exportProject(){saveProject();download(new Blob([snapshot()],{type:'application/json'}),(state.projectName||'SimpleRig')+'.simplerig.json')}
function importProject(file){const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);d.projectId=uid();d.projectName=(d.projectName||'Imported')+' Imported';Object.assign(state,d);$('projectName').value=state.projectName;$('harnessNotes').value=state.harnessNotes||'';loadBackground();renderAll();saveProject()}catch{alert('Invalid SimpleRig project file.')}};r.readAsText(file)}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function img(src,cors=false){if(imageCache.has(src))return imageCache.get(src);const i=new Image();if(cors)i.crossOrigin='anonymous';i.onload=draw;i.src=src;imageCache.set(src,i);return i}
function loadBackground(){bgImage=null;if(!state.background){draw();return}bgImage=new Image();bgImage.onload=draw;bgImage.src=state.background}
function makeQuad(x,y,w,h){return[{x:x-w/2,y:y-h/2},{x:x+w/2,y:y-h/2},{x:x+w/2,y:y+h/2},{x:x-w/2,y:y+h/2}]}
function centroid(q){return{x:q.reduce((s,p)=>s+p.x,0)/4,y:q.reduce((s,p)=>s+p.y,0)/4}}
function bbox(q){const xs=q.map(p=>p.x),ys=q.map(p=>p.y);return{x:Math.min(...xs),y:Math.min(...ys),w:Math.max(...xs)-Math.min(...xs),h:Math.max(...ys)-Math.min(...ys)}}
function rotateQuad(q,a,c=centroid(q)){a*=Math.PI/180;const ca=Math.cos(a),sa=Math.sin(a);return q.map(p=>({x:c.x+(p.x-c.x)*ca-(p.y-c.y)*sa,y:c.y+(p.x-c.x)*sa+(p.y-c.y)*ca}))}
function bilerp(q,u,v){return{x:(1-u)*(1-v)*q[0].x+u*(1-v)*q[1].x+u*v*q[2].x+(1-u)*v*q[3].x,y:(1-u)*(1-v)*q[0].y+u*(1-v)*q[1].y+u*v*q[2].y+(1-u)*v*q[3].y}}
function worldPoint(o,p){return bilerp(o.quad,p.u,p.v)}
function pointInPoly(x,y,p){let inside=false;for(let i=0,j=p.length-1;i<p.length;j=i++){const xi=p[i].x,yi=p[i].y,xj=p[j].x,yj=p[j].y;if(((yi>y)!=(yj>y))&&(x<(xj-xi)*(y-yi)/(yj-yi)+xi))inside=!inside}return inside}
function distanceSegment(p,a,b){const A=p.x-a.x,B=p.y-a.y,C=b.x-a.x,D=b.y-a.y,t=clamp((A*C+B*D)/(C*C+D*D||1),0,1);return Math.hypot(p.x-(a.x+t*C),p.y-(a.y+t*D))}
function cpoint(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)/state.zoom,y:(e.clientY-r.top)/state.zoom}}
function layerVisible(id){return state.layers.find(l=>l.id===id)?.visible!==false}
function layerLocked(id){return state.layers.find(l=>l.id===id)?.locked===true}
function selected(){return state.objects.find(o=>o.id===state.selectedId)||state.lines.find(l=>l.id===state.selectedId)}
function endpoint(line,key){const a=line[key];if(a?.objectId){const o=state.objects.find(x=>x.id===a.objectId),cp=o?.points?.find(x=>x.id===a.pointId);if(o&&cp)return worldPoint(o,cp)}return{x:a?.x||0,y:a?.y||0}}
function nearestConnection(p,max=20,exclude=null){let best=null;for(const o of state.objects){if(o.id===exclude)continue;for(const cp of o.points||[]){const w=worldPoint(o,cp),d=Math.hypot(p.x-w.x,p.y-w.y);if(d<max&&(!best||d<best.d))best={objectId:o.id,pointId:cp.id,x:w.x,y:w.y,d}}}return best}
function addAsset(a,x,y){pushHistory();const points=(a.points||[]).map(([name,u,v])=>({id:uid(),name,u,v}));const o={id:uid(),type:a.type||'image',name:a.name||'Asset',src:a.src,w:a.w||180,h:a.h||120,quad:makeQuad(x,y,a.w||180,a.h||120),rotation:0,opacity:1,flipH:false,flipV:false,color:'#111827',notes:'',layer:(a.type==='performer'?'performers':'equipment'),points,remote:!!a.remote,source:a.source||'',licence:a.licence||''};state.objects.push(o);state.selectedId=o.id;renderAll()}
function renderAssets(filter=''){const el=$('assetLibrary');el.innerHTML='';assets.filter(a=>a.name.toLowerCase().includes(filter.toLowerCase())).forEach(a=>{const d=document.createElement('div');d.className='asset-item';d.draggable=true;d.dataset.asset=JSON.stringify(a);d.innerHTML=`<img src="${a.src}" alt=""><span>${a.name}</span>`;d.addEventListener('dragstart',e=>e.dataTransfer.setData('application/x-simplerig',d.dataset.asset));d.addEventListener('click',()=>addAsset(a,canvas.width/2,canvas.height/2));el.appendChild(d)})}
function drawGrid(){if(!$('gridToggle').checked)return;ctx.save();ctx.strokeStyle='#e5e7eb';for(let x=0;x<canvas.width;x+=20){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,canvas.height);ctx.stroke()}for(let y=0;y<canvas.height;y+=20){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(canvas.width,y);ctx.stroke()}ctx.restore()}
function drawTriangle(im,s0,s1,s2,d0,d1,d2){const den=s0.x*(s1.y-s2.y)+s1.x*(s2.y-s0.y)+s2.x*(s0.y-s1.y);if(Math.abs(den)<1e-6)return;const a=(d0.x*(s1.y-s2.y)+d1.x*(s2.y-s0.y)+d2.x*(s0.y-s1.y))/den,c=(d0.x*(s2.x-s1.x)+d1.x*(s0.x-s2.x)+d2.x*(s1.x-s0.x))/den,e=(d0.x*(s1.x*s2.y-s2.x*s1.y)+d1.x*(s2.x*s0.y-s0.x*s2.y)+d2.x*(s0.x*s1.y-s1.x*s0.y))/den,b=(d0.y*(s1.y-s2.y)+d1.y*(s2.y-s0.y)+d2.y*(s0.y-s1.y))/den,d=(d0.y*(s2.x-s1.x)+d1.y*(s0.x-s2.x)+d2.y*(s1.x-s0.x))/den,f=(d0.y*(s1.x*s2.y-s2.x*s1.y)+d1.y*(s2.x*s0.y-s0.x*s2.y)+d2.y*(s0.x*s1.y-s1.x*s0.y))/den;ctx.save();ctx.beginPath();ctx.moveTo(d0.x,d0.y);ctx.lineTo(d1.x,d1.y);ctx.lineTo(d2.x,d2.y);ctx.closePath();ctx.clip();ctx.transform(a,b,c,d,e,f);ctx.drawImage(im,0,0);ctx.restore()}
function drawWarp(im,q,fh,fv){if(!im.complete||!im.naturalWidth)return;const n=8,sw=im.naturalWidth,sh=im.naturalHeight;for(let y=0;y<n;y++)for(let x=0;x<n;x++){const uu=[x/n,(x+1)/n],vv=[y/n,(y+1)/n],u0=(fh?1-uu[0]:uu[0]),u1=(fh?1-uu[1]:uu[1]),v0=(fv?1-vv[0]:vv[0]),v1=(fv?1-vv[1]:vv[1]);const d00=bilerp(q,x/n,y/n),d10=bilerp(q,(x+1)/n,y/n),d11=bilerp(q,(x+1)/n,(y+1)/n),d01=bilerp(q,x/n,(y+1)/n),s00={x:u0*sw,y:v0*sh},s10={x:u1*sw,y:v0*sh},s11={x:u1*sw,y:v1*sh},s01={x:u0*sw,y:v1*sh};drawTriangle(im,s00,s10,s11,d00,d10,d11);drawTriangle(im,s00,s11,s01,d00,d11,d01)}}
function drawObject(o){if(!layerVisible(o.layer))return;ctx.save();ctx.globalAlpha=o.opacity;drawWarp(img(o.src,o.remote),o.quad,o.flipH,o.flipV);ctx.restore();if(o.id===state.selectedId){ctx.save();ctx.strokeStyle='#0ea5e9';ctx.lineWidth=3;ctx.setLineDash([8,4]);ctx.beginPath();ctx.moveTo(o.quad[0].x,o.quad[0].y);o.quad.slice(1).forEach(p=>ctx.lineTo(p.x,p.y));ctx.closePath();ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#0ea5e9';o.quad.forEach(p=>ctx.fillRect(p.x-7,p.y-7,14,14));for(const cp of o.points||[]){const w=worldPoint(o,cp);ctx.beginPath();ctx.arc(w.x,w.y,7,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#fff';ctx.stroke()}ctx.restore()}}
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);if(bgImage){ctx.save();ctx.globalAlpha=state.backgroundOpacity;const s=Math.min(canvas.width/bgImage.width,canvas.height/bgImage.height),w=bgImage.width*s,h=bgImage.height*s;ctx.drawImage(bgImage,(canvas.width-w)/2,(canvas.height-h)/2,w,h);ctx.restore()}drawGrid();for(const l of state.lines){if(!layerVisible(l.layer))continue;const a=endpoint(l,'start'),b=endpoint(l,'end');ctx.save();ctx.strokeStyle=l.color||'#111827';ctx.lineWidth=l.type==='measure'?2:4;if(l.type==='measure')ctx.setLineDash([9,5]);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();if(l.type==='measure'){ctx.fillStyle='#111827';ctx.font='15px system-ui';ctx.fillText((Math.hypot(b.x-a.x,b.y-a.y)/100).toFixed(2)+' m',(a.x+b.x)/2+8,(a.y+b.y)/2-8)}if(l.id===state.selectedId){ctx.fillStyle='#0ea5e9';for(const p of [a,b]){ctx.beginPath();ctx.arc(p.x,p.y,8,0,Math.PI*2);ctx.fill()}}ctx.restore()}state.objects.forEach(drawObject);if(drawing){ctx.save();ctx.strokeStyle='#0ea5e9';ctx.lineWidth=3;ctx.setLineDash([8,5]);ctx.beginPath();ctx.moveTo(drawing.x1,drawing.y1);ctx.lineTo(drawing.x2,drawing.y2);ctx.stroke();ctx.restore()}}
function objectAt(p){for(let i=state.objects.length-1;i>=0;i--){const o=state.objects[i];if(layerVisible(o.layer)&&pointInPoly(p.x,p.y,o.quad))return o}for(let i=state.lines.length-1;i>=0;i--){const l=state.lines[i],a=endpoint(l,'start'),b=endpoint(l,'end');if(distanceSegment(p,a,b)<10)return l}return null}
function cornerAt(o,p){for(let i=0;i<4;i++)if(Math.hypot(o.quad[i].x-p.x,o.quad[i].y-p.y)<15)return i;return-1}

canvas.addEventListener('pointerdown',e=>{const p=cpoint(e);if(state.tool==='line'||state.tool==='measure'){const snap=$('snapToggle').checked?nearestConnection(p):null;drawing={type:state.tool,x1:snap?snap.x:p.x,y1:snap?snap.y:p.y,x2:p.x,y2:p.y,startSnap:snap};canvas.setPointerCapture(e.pointerId);return}if(state.tool==='label'){const t=prompt('Label text:');if(t){pushHistory();state.lines.push({id:uid(),type:'label',name:t,start:{x:p.x,y:p.y},end:{x:p.x+1,y:p.y},color:'#111827',layer:'annotations'});renderAll()}return}const cur=selected();if(cur?.quad){const ci=cornerAt(cur,p);if(ci>=0){pushHistory();drag={kind:state.perspective?'corner':'scale',index:ci,start:p,orig:JSON.parse(JSON.stringify(cur.quad))};canvas.setPointerCapture(e.pointerId);return}}const item=objectAt(p);state.selectedId=item?.id||null;if(item?.quad&&!layerLocked(item.layer)){pushHistory();drag={kind:'moveObject',start:p,orig:JSON.parse(JSON.stringify(item.quad))};canvas.setPointerCapture(e.pointerId)}else if(item&&!item.quad&&!layerLocked(item.layer)){pushHistory();const a=endpoint(item,'start'),b=endpoint(item,'end');drag={kind:'moveLine',start:p,orig:{a,b}};canvas.setPointerCapture(e.pointerId)}else if(state.tool==='pan'){drag={kind:'pan',sx:e.clientX,sy:e.clientY,sl:viewport.scrollLeft,st:viewport.scrollTop};canvas.setPointerCapture(e.pointerId)}renderAll()});
canvas.addEventListener('pointermove',e=>{const p=cpoint(e);if(drawing){const snap=$('snapToggle').checked?nearestConnection(p):null;drawing.x2=snap?snap.x:p.x;drawing.y2=snap?snap.y:p.y;drawing.endSnap=snap;draw();return}if(!drag)return;if(drag.kind==='pan'){viewport.scrollLeft=drag.sl-(e.clientX-drag.sx);viewport.scrollTop=drag.st-(e.clientY-drag.sy);return}const s=selected();if(drag.kind==='moveObject'&&s?.quad){let dx=p.x-drag.start.x,dy=p.y-drag.start.y;if($('snapToggle').checked){dx=Math.round(dx/10)*10;dy=Math.round(dy/10)*10}s.quad=drag.orig.map(q=>({x:q.x+dx,y:q.y+dy}))}else if(drag.kind==='corner'&&s?.quad){s.quad[drag.index]={x:p.x,y:p.y}}else if(drag.kind==='scale'&&s?.quad){const oi=(drag.index+2)%4,opp=drag.orig[oi],oc=drag.orig[drag.index],sx=(p.x-opp.x)/(oc.x-opp.x||1),sy=(p.y-opp.y)/(oc.y-opp.y||1);s.quad=drag.orig.map(q=>({x:opp.x+(q.x-opp.x)*sx,y:opp.y+(q.y-opp.y)*sy}))}else if(drag.kind==='moveLine'&&s&&!s.quad){const dx=p.x-drag.start.x,dy=p.y-drag.start.y;s.start={x:drag.orig.a.x+dx,y:drag.orig.a.y+dy};s.end={x:drag.orig.b.x+dx,y:drag.orig.b.y+dy}}renderAll()});
canvas.addEventListener('pointerup',e=>{if(drawing){pushHistory();state.lines.push({id:uid(),type:drawing.type,name:drawing.type==='measure'?'Measurement':'Rig line',start:drawing.startSnap?{objectId:drawing.startSnap.objectId,pointId:drawing.startSnap.pointId}:{x:drawing.x1,y:drawing.y1},end:drawing.endSnap?{objectId:drawing.endSnap.objectId,pointId:drawing.endSnap.pointId}:{x:drawing.x2,y:drawing.y2},color:drawing.type==='measure'?'#dc2626':'#111827',layer:drawing.type==='measure'?'measurements':'rigging',notes:''});drawing=null;renderAll()}drag=null});
canvas.addEventListener('dragover',e=>e.preventDefault());canvas.addEventListener('drop',e=>{e.preventDefault();const raw=e.dataTransfer.getData('application/x-simplerig');if(raw){const p=cpoint(e);addAsset(JSON.parse(raw),p.x,p.y)}});

function renderInspector(){const s=selected();$('emptyInspector').hidden=!!s;$('inspector').hidden=!s;if(!s)return;$('objName').value=s.name||'';$('objColor').value=s.color||'#111827';$('objNotes').value=s.notes||'';$('imageControls').hidden=!s.quad;if(s.quad){const b=bbox(s.quad);$('objWidth').value=Math.round(b.w);$('objHeight').value=Math.round(b.h);$('objRotation').value=Math.round(s.rotation||0);$('objOpacity').value=s.opacity||1;$('connectionInfo').textContent=(s.points||[]).map(p=>p.name).join(', ')||'No defined points.'}else $('connectionInfo').textContent='Lines can attach to blue object connection points.'}
function updateInspector(){const s=selected();if(!s)return;pushHistory();s.name=$('objName').value;s.color=$('objColor').value;s.notes=$('objNotes').value;if(s.quad){const b=bbox(s.quad),c=centroid(s.quad),nw=Math.max(10,+$('objWidth').value),nh=Math.max(10,+$('objHeight').value),sx=nw/(b.w||1),sy=nh/(b.h||1);s.quad=s.quad.map(p=>({x:c.x+(p.x-c.x)*sx,y:c.y+(p.y-c.y)*sy}));const delta=+$('objRotation').value-(s.rotation||0);s.quad=rotateQuad(s.quad,delta,c);s.rotation=+$('objRotation').value;s.opacity=+$('objOpacity').value}renderAll()}
function deleteSelected(){if(!state.selectedId)return;pushHistory();state.objects=state.objects.filter(o=>o.id!==state.selectedId);state.lines=state.lines.filter(l=>l.id!==state.selectedId);state.selectedId=null;renderAll()}
function duplicate(){const s=selected();if(!s)return;pushHistory();const c=JSON.parse(JSON.stringify(s));c.id=uid();c.name+=' Copy';if(c.quad)c.quad=c.quad.map(p=>({x:p.x+30,y:p.y+30}));else{c.start={x:endpoint(c,'start').x+30,y:endpoint(c,'start').y+30};c.end={x:endpoint(c,'end').x+30,y:endpoint(c,'end').y+30}}(c.quad?state.objects:state.lines).push(c);state.selectedId=c.id;renderAll()}
function resetTransform(){const s=selected();if(!s?.quad)return;pushHistory();const c=centroid(s.quad),b=bbox(s.quad);s.quad=makeQuad(c.x,c.y,b.w,b.h);s.rotation=0;s.flipH=s.flipV=false;renderAll()}
function flip(k){const s=selected();if(!s?.quad)return;pushHistory();s[k]=!s[k];renderAll()}
function renderLayers(){const el=$('layerList');el.innerHTML='';state.layers.forEach(l=>{const r=document.createElement('div');r.className='layer-row';r.innerHTML=`<button data-v>${l.visible?'👁':'🚫'}</button><button data-l>${l.locked?'🔒':'🔓'}</button><span>${l.name}</span>`;r.querySelector('[data-v]').onclick=()=>{pushHistory();l.visible=!l.visible;renderAll()};r.querySelector('[data-l]').onclick=()=>{pushHistory();l.locked=!l.locked;renderAll()};el.appendChild(r)})}
function renderAll(){draw();renderInspector();renderLayers();renderDrawingLibrary();renderCalendar();renderProjects()}

function saveDrawing(){state.selectedId=null;draw();try{const data=canvas.toDataURL('image/png');state.drawings.push({id:uid(),name:prompt('Drawing name:','Rig plan '+(state.drawings.length+1))||'Rig plan',image:data,created:new Date().toISOString()});pushHistory();renderDrawingLibrary()}catch{alert('A remote image has blocked saving. Download it and import it locally first.')}}
function renderDrawingLibrary(){const el=$('drawingLibrary');if(!el)return;el.innerHTML='';if(!state.drawings.length)el.innerHTML='<p>No saved drawings yet.</p>';state.drawings.forEach(d=>{const c=document.createElement('div');c.className='drawing-card';c.draggable=true;c.dataset.id=d.id;c.innerHTML=`<img src="${d.image}" alt=""><h4>${d.name}</h4><p>Drag onto a calendar date</p><button data-load>Load drawing</button> <button data-delete>Delete</button>`;c.addEventListener('dragstart',e=>e.dataTransfer.setData('text/simplerig-drawing',d.id));c.querySelector('[data-load]').onclick=()=>download(dataUrlBlob(d.image),d.name+'.png');c.querySelector('[data-delete]').onclick=()=>{state.drawings=state.drawings.filter(x=>x.id!==d.id);state.calendar=state.calendar.filter(x=>x.drawingId!==d.id);pushHistory();renderAll()};el.appendChild(c)})}
function dataUrlBlob(url){const [meta,data]=url.split(','),mime=meta.match(/:(.*?);/)[1],bin=atob(data),arr=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)arr[i]=bin.charCodeAt(i);return new Blob([arr],{type:mime})}
function renderCalendar(){const el=$('calendarGrid');if(!el)return;el.innerHTML='';['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].forEach(x=>{const h=document.createElement('div');h.className='calendar-head';h.textContent=x;el.appendChild(h)});const first=new Date(state.year,state.month,1),off=(first.getDay()+6)%7,start=new Date(state.year,state.month,1-off);$('calendarTitle').textContent=first.toLocaleString('en-GB',{month:'long',year:'numeric'});for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const key=d.toISOString().slice(0,10),cell=document.createElement('div');cell.className='calendar-day'+(d.getMonth()!==state.month?' other':'');cell.innerHTML=`<div class="daynum">${d.getDate()}</div>`;state.calendar.filter(x=>x.date===key).forEach(item=>{const dr=state.drawings.find(x=>x.id===item.drawingId);if(!dr)return;const card=document.createElement('div');card.className='calendar-drawing';card.draggable=true;card.dataset.id=item.id;card.innerHTML=`<img src="${dr.image}" alt=""><div>${dr.name}</div>`;card.addEventListener('dragstart',e=>e.dataTransfer.setData('text/calendar-item',item.id));card.ondblclick=()=>{if(confirm('Remove this drawing from the date?')){state.calendar=state.calendar.filter(x=>x.id!==item.id);pushHistory();renderCalendar()}};cell.appendChild(card)});cell.addEventListener('dragover',e=>e.preventDefault());cell.addEventListener('drop',e=>{e.preventDefault();const drawingId=e.dataTransfer.getData('text/simplerig-drawing'),itemId=e.dataTransfer.getData('text/calendar-item');if(drawingId)state.calendar.push({id:uid(),drawingId,date:key});else if(itemId){const it=state.calendar.find(x=>x.id===itemId);if(it)it.date=key}pushHistory();renderCalendar()});el.appendChild(cell)}}
function exportICS(){let txt='BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//SimpleRig//EN\r\n';for(const item of state.calendar){const d=state.drawings.find(x=>x.id===item.drawingId);if(!d)continue;txt+=`BEGIN:VEVENT\r\nUID:${item.id}@simplerig\r\nDTSTART;VALUE=DATE:${item.date.replaceAll('-','')}\r\nSUMMARY:${d.name.replace(/[,;\\]/g,' ')}\r\nDESCRIPTION:SimpleRig drawing scheduled for ${state.projectName.replace(/[,;\\]/g,' ')}\r\nEND:VEVENT\r\n`}txt+='END:VCALENDAR\r\n';download(new Blob([txt],{type:'text/calendar'}),(state.projectName||'SimpleRig')+'-calendar.ics')}
function renderProjects(){const el=$('projectsGrid');if(!el)return;el.innerHTML='';Object.values(projectMap()).sort((a,b)=>b.updated.localeCompare(a.updated)).forEach(p=>{const c=document.createElement('div');c.className='project-card';c.innerHTML=`<h3>${p.name.replace(/[<>]/g,'')}</h3><p>Updated ${new Date(p.updated).toLocaleString('en-GB')}</p><div class="project-actions"><button data-open>Open</button><button data-copy>Duplicate</button><button data-delete>Delete</button></div>`;c.querySelector('[data-open]').onclick=()=>loadProject(p.id);c.querySelector('[data-copy]').onclick=()=>{const ps=projectMap(),d=JSON.parse(p.data),id=uid();d.projectId=id;d.projectName+=' Copy';ps[id]={id,name:d.projectName,updated:new Date().toISOString(),data:JSON.stringify(d)};localStorage.setItem('simplerig-pro-projects',JSON.stringify(ps));renderProjects()};c.querySelector('[data-delete]').onclick=()=>{if(confirm('Delete this project?')){const ps=projectMap();delete ps[p.id];localStorage.setItem('simplerig-pro-projects',JSON.stringify(ps));renderProjects()}};el.appendChild(c)})}
async function liveSearch(){const q=$('liveQuery').value.trim();if(!q)return;$('liveStatus').textContent='Searching…';$('liveResults').innerHTML='';const url='https://commons.wikimedia.org/w/api.php?origin=*&action=query&format=json&generator=search&gsrnamespace=6&gsrsearch='+encodeURIComponent(q)+'&gsrlimit=12&prop=imageinfo&iiprop=url|extmetadata&iiurlwidth=300';try{const r=await fetch(url),data=await r.json(),pages=Object.values(data.query?.pages||{});$('liveStatus').textContent=pages.length+' results';for(const p of pages){const inf=p.imageinfo?.[0];if(!inf)continue;const card=document.createElement('div');card.className='live-card';const licence=inf.extmetadata?.LicenseShortName?.value||'See source';card.innerHTML=`<img src="${inf.thumburl||inf.url}" alt=""><p title="${p.title}">${p.title.replace(/^File:/,'')}</p><p>${licence}</p><button>Add</button>`;card.querySelector('button').onclick=()=>addAsset({name:p.title.replace(/^File:/,''),type:'image',src:inf.url,w:220,h:160,points:[],remote:true,source:inf.descriptionurl,licence},canvas.width/2,canvas.height/2);$('liveResults').appendChild(card)}}catch(e){$('liveStatus').textContent='Search failed. Check your connection.'}}
function calculate(){const kg=Math.max(0,+$('calcLoad').value||0),r=Math.max(1,+$('calcRatio').value||1),eff=clamp(+$('calcEfficiency').value||100,1,100)/100,dis=Math.max(.1,+$('calcDisadvantage').value||1),reds=Math.max(0,+$('calcRedirects').value||0),load=kg*9.81,ideal=load/r,actual=ideal/eff*dis;$('rLoad').textContent=load.toFixed(0)+' N';$('rIdeal').textContent=ideal.toFixed(0)+' N';$('rActual').textContent=actual.toFixed(0)+' N';$('rKg').textContent=(actual/9.81).toFixed(1)+' kgf';$('rTension').textContent=actual.toFixed(0)+' N';$('rRedirect').textContent=reds?(actual*2).toFixed(0)+' N × '+reds:'None';$('rTravel').textContent=r.toFixed(1)+' m';$('rFactor').textContent=(r*eff/dis).toFixed(2)+':1'}
function switchView(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$(v+'View').classList.add('active');renderAll()}

document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>switchView(b.dataset.view));
document.querySelectorAll('.tool[data-tool]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tool[data-tool]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.tool=b.dataset.tool});
$('saveBtn').onclick=saveProject;$('exportProjectBtn').onclick=exportProject;$('importProjectInput').onchange=e=>e.target.files[0]&&importProject(e.target.files[0]);$('projectName').oninput=pushHistory;$('newProjectBtn').onclick=newProject;
$('deleteSelectedBtn').onclick=deleteSelected;$('duplicateBtn').onclick=duplicate;$('flipHBtn').onclick=()=>flip('flipH');$('flipVBtn').onclick=()=>flip('flipV');$('resetTransformBtn').onclick=resetTransform;$('perspectiveBtn').onclick=()=>{state.perspective=!state.perspective;$('perspectiveBtn').classList.toggle('active',state.perspective)};
['objName','objWidth','objHeight','objRotation','objOpacity','objColor','objNotes'].forEach(id=>$(id).onchange=updateInspector);
$('backgroundInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{pushHistory();state.background=r.result;loadBackground()};r.readAsDataURL(f)};$('backgroundOpacity').oninput=e=>{state.backgroundOpacity=+e.target.value;pushHistory();draw()};$('clearBackgroundBtn').onclick=()=>{pushHistory();state.background=null;loadBackground()};
$('customAssetInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>addAsset({name:f.name.replace(/\.[^.]+$/,''),type:'image',src:r.result,w:230,h:160,points:[]},canvas.width/2,canvas.height/2);r.readAsDataURL(f)};$('assetFilter').oninput=e=>renderAssets(e.target.value);
$('zoomInBtn').onclick=()=>setZoom(state.zoom+.1);$('zoomOutBtn').onclick=()=>setZoom(state.zoom-.1);$('fitBtn').onclick=()=>setZoom(Math.min((viewport.clientWidth-50)/canvas.width,(viewport.clientHeight-50)/canvas.height));$('undoBtn').onclick=()=>{if(state.history.length){state.future.push(snapshot());restore(state.history.pop())}};$('redoBtn').onclick=()=>{if(state.future.length){state.history.push(snapshot());restore(state.future.pop())}};
$('exportPngBtn').onclick=()=>{state.selectedId=null;draw();try{canvas.toBlob(b=>download(b,(state.projectName||'SimpleRig')+'.png'))}catch{alert('A remote image blocks export. Download and re-import it locally.')}};$('saveDrawingBtn').onclick=saveDrawing;
$('liveSearchBtn').onclick=liveSearch;$('liveQuery').onkeydown=e=>{if(e.key==='Enter')liveSearch()};$('googleSearchBtn').onclick=()=>window.open('https://www.google.com/search?tbm=isch&q='+encodeURIComponent($('liveQuery').value||'stunt rigging equipment'),'_blank');
$('prevMonthBtn').onclick=()=>{state.month--;if(state.month<0){state.month=11;state.year--}renderCalendar()};$('nextMonthBtn').onclick=()=>{state.month++;if(state.month>11){state.month=0;state.year++}renderCalendar()};$('exportIcsBtn').onclick=exportICS;$('printCalendarBtn').onclick=()=>window.print();
$('saveHarnessNotesBtn').onclick=()=>{state.harnessNotes=$('harnessNotes').value;pushHistory();saveProject()};
['calcLoad','calcRatio','calcEfficiency','calcDisadvantage','calcRedirects'].forEach(id=>$(id).oninput=calculate);$('calculateBtn').onclick=calculate;
function setZoom(z){state.zoom=clamp(z,.25,2);canvas.style.transform=`scale(${state.zoom})`;canvas.style.marginRight=`${canvas.width*(state.zoom-1)}px`;canvas.style.marginBottom=`${canvas.height*(state.zoom-1)}px`;$('zoomLabel').textContent=Math.round(state.zoom*100)+'%'}
window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();saveProject()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();$('undoBtn').click()}if(e.key==='Delete'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName))deleteSelected()});
const current=localStorage.getItem('simplerig-pro-current'),ps=projectMap();if(current&&ps[current]){Object.assign(state,JSON.parse(ps[current].data));$('projectName').value=state.projectName;$('harnessNotes').value=state.harnessNotes||'';loadBackground()}else saveProject();
renderAssets();setZoom(1);renderAll();calculate();
})();
