(()=>{'use strict';
const $=id=>document.getElementById(id),uid=()=>Math.random().toString(36).slice(2),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const canvas=$('canvas'),ctx=canvas.getContext('2d'),viewport=$('viewport');
const assets=[['Pulley','◉',70,70,'#f59e0b'],['Double Pulley','◎',90,70,'#fb923c'],['Tie-off','⊗',70,70,'#64748b'],['Performer','🧍',70,120,'#2563eb'],['Truss','▦',180,55,'#475569'],['Rope Grab','◆',65,65,'#7c3aed'],['Winch','⚙',95,80,'#111827'],['Telehandler','🚜',190,105,'#facc15'],['Shackle','∪',60,70,'#6b7280'],['Carabiner','⛓',55,75,'#9ca3af'],['Anchor','⚓',80,80,'#334155'],['Harness','⌁',80,110,'#0f172a']].map(a=>({name:a[0],icon:a[1],w:a[2],h:a[3],color:a[4],type:a[0].toLowerCase().replaceAll(' ','')}));
const defaultLayers=[['background','Background',1,1],['rigging','Rigging',1,0],['performers','Performers',1,0],['equipment','Equipment',1,0],['annotations','Annotations',1,0],['measurements','Measurements',1,0]].map(x=>({id:x[0],name:x[1],visible:!!x[2],locked:!!x[3]}));
const state={projectId:uid(),projectName:'Untitled Project',objects:[],lines:[],background:null,backgroundOpacity:.8,layers:structuredClone(defaultLayers),selectedId:null,tool:'select',mode:'move',zoom:1,history:[],future:[],calendar:[],month:new Date().getMonth(),year:new Date().getFullYear(),customAssets:[]};
let bg=null,drag=null,drawing=null,pendingDate=null;const cache=new Map();
const snap=n=>Math.round(n/20)*20,centroid=q=>({x:q.reduce((s,p)=>s+p.x,0)/4,y:q.reduce((s,p)=>s+p.y,0)/4}),bbox=q=>{const x=q.map(p=>p.x),y=q.map(p=>p.y);return{x:Math.min(...x),y:Math.min(...y),w:Math.max(...x)-Math.min(...x),h:Math.max(...y)-Math.min(...y)}},quad=(x,y,w,h)=>[{x:x-w/2,y:y-h/2},{x:x+w/2,y:y-h/2},{x:x+w/2,y:y+h/2},{x:x-w/2,y:y+h/2}],dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
function visible(id){return state.layers.find(l=>l.id===id)?.visible!==false}function locked(id){return state.layers.find(l=>l.id===id)?.locked===true}function layerFor(t){return t==='performer'||t==='harness'?'performers':t==='text'?'annotations':'equipment'}
function pointIn(x,y,p){let inside=false;for(let i=0,j=p.length-1;i<p.length;j=i++){const a=p[i],b=p[j];if((a.y>y)!=(b.y>y)&&x<(b.x-a.x)*(y-a.y)/(b.y-a.y)+a.x)inside=!inside}return inside}
function rotate(q,deg,c=centroid(q)){const a=deg*Math.PI/180,ca=Math.cos(a),sa=Math.sin(a);return q.map(p=>({x:c.x+(p.x-c.x)*ca-(p.y-c.y)*sa,y:c.y+(p.x-c.x)*sa+(p.y-c.y)*ca}))}
function snapshot(){return JSON.stringify({projectId:state.projectId,projectName:state.projectName,objects:state.objects,lines:state.lines,background:state.background,backgroundOpacity:state.backgroundOpacity,layers:state.layers,calendar:state.calendar,customAssets:state.customAssets})}
function projects(){try{return JSON.parse(localStorage.getItem('simplerig2d-projects')||'{}')}catch{return{}}}function push(){state.history.push(snapshot());if(state.history.length>60)state.history.shift();state.future=[];$('saveStatus').textContent='Unsaved changes';clearTimeout(push.t);push.t=setTimeout(save,700)}
function save(){state.projectName=$('projectName').value.trim()||'Untitled Project';const p=projects();p[state.projectId]={id:state.projectId,name:state.projectName,updated:new Date().toISOString(),data:snapshot()};localStorage.setItem('simplerig2d-projects',JSON.stringify(p));localStorage.setItem('simplerig2d-current',state.projectId);$('saveStatus').textContent='Saved locally';renderProjects()}
function loadBg(){bg=null;if(!state.background){draw();return}bg=new Image();bg.onload=draw;bg.src=state.background}
function img(src,remote){if(cache.has(src))return cache.get(src);const i=new Image();if(remote)i.crossOrigin='anonymous';i.onload=draw;i.src=src;cache.set(src,i);return i}
function addAsset(a,x=800,y=500){push();const o={id:uid(),name:a.name||'Asset',type:a.type||'image',icon:a.icon||'',color:a.color||'#475569',image:a.image||null,remote:!!a.remote,sourcePage:a.sourcePage||'',opacity:1,notes:'',rotation:0,flipH:false,flipV:false,layer:layerFor(a.type),quad:quad(x,y,a.w||200,a.h||140)};state.objects.push(o);state.selectedId=o.id;renderAll()}
function selected(){return state.objects.find(o=>o.id===state.selectedId)||state.lines.find(l=>l.id===state.selectedId)}
function renderAssets(f=''){const el=$('assetLibrary');el.innerHTML='';[...assets,...state.customAssets].filter(a=>a.name.toLowerCase().includes(f.toLowerCase())).forEach(a=>{const d=document.createElement('div');d.className='asset-item';d.draggable=true;d.innerHTML=`<div class="asset-icon">${a.image?'🖼️':a.icon}</div><div>${a.name}</div>`;d.addEventListener('dragstart',e=>e.dataTransfer.setData('application/x-simplerig',JSON.stringify(a)));d.onclick=()=>addAsset(a);el.appendChild(d)})}
function bilerp(q,u,v){return{x:(1-u)*(1-v)*q[0].x+u*(1-v)*q[1].x+u*v*q[2].x+(1-u)*v*q[3].x,y:(1-u)*(1-v)*q[0].y+u*(1-v)*q[1].y+u*v*q[2].y+(1-u)*v*q[3].y}}
function tri(im,s0,s1,s2,d0,d1,d2){const z=s0.x*(s1.y-s2.y)+s1.x*(s2.y-s0.y)+s2.x*(s0.y-s1.y);if(Math.abs(z)<1e-5)return;const a=(d0.x*(s1.y-s2.y)+d1.x*(s2.y-s0.y)+d2.x*(s0.y-s1.y))/z,c=(d0.x*(s2.x-s1.x)+d1.x*(s0.x-s2.x)+d2.x*(s1.x-s0.x))/z,e=(d0.x*(s1.x*s2.y-s2.x*s1.y)+d1.x*(s2.x*s0.y-s0.x*s2.y)+d2.x*(s0.x*s1.y-s1.x*s0.y))/z,b=(d0.y*(s1.y-s2.y)+d1.y*(s2.y-s0.y)+d2.y*(s0.y-s1.y))/z,d=(d0.y*(s2.x-s1.x)+d1.y*(s0.x-s2.x)+d2.y*(s1.x-s0.x))/z,f=(d0.y*(s1.x*s2.y-s2.x*s1.y)+d1.y*(s2.x*s0.y-s0.x*s2.y)+d2.y*(s0.x*s1.y-s1.x*s0.y))/z;ctx.save();ctx.beginPath();ctx.moveTo(d0.x,d0.y);ctx.lineTo(d1.x,d1.y);ctx.lineTo(d2.x,d2.y);ctx.closePath();ctx.clip();ctx.transform(a,b,c,d,e,f);ctx.drawImage(im,0,0);ctx.restore()}
function warp(im,q,fh,fv){if(!im?.complete||!im.naturalWidth)return;const n=8,w=im.naturalWidth,h=im.naturalHeight;for(let y=0;y<n;y++)for(let x=0;x<n;x++){let u0=x/n,u1=(x+1)/n,v0=y/n,v1=(y+1)/n;if(fh){u0=1-u0;u1=1-u1}if(fv){v0=1-v0;v1=1-v1}const d00=bilerp(q,x/n,y/n),d10=bilerp(q,(x+1)/n,y/n),d11=bilerp(q,(x+1)/n,(y+1)/n),d01=bilerp(q,x/n,(y+1)/n),s00={x:u0*w,y:v0*h},s10={x:u1*w,y:v0*h},s11={x:u1*w,y:v1*h},s01={x:u0*w,y:v1*h};tri(im,s00,s10,s11,d00,d10,d11);tri(im,s00,s11,s01,d00,d11,d01)}}
function drawSelection(o){ctx.save();ctx.strokeStyle='#0ea5e9';ctx.lineWidth=3;ctx.setLineDash([8,4]);ctx.beginPath();ctx.moveTo(o.quad[0].x,o.quad[0].y);for(let i=1;i<4;i++)ctx.lineTo(o.quad[i].x,o.quad[i].y);ctx.closePath();ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#0ea5e9';o.quad.forEach(p=>ctx.fillRect(p.x-7,p.y-7,14,14));const c=centroid(o.quad),t={x:(o.quad[0].x+o.quad[1].x)/2,y:(o.quad[0].y+o.quad[1].y)/2},v={x:t.x-c.x,y:t.y-c.y},l=Math.hypot(v.x,v.y)||1,r={x:t.x+v.x/l*35,y:t.y+v.y/l*35};ctx.beginPath();ctx.moveTo(t.x,t.y);ctx.lineTo(r.x,r.y);ctx.stroke();ctx.beginPath();ctx.arc(r.x,r.y,8,0,Math.PI*2);ctx.fill();ctx.restore()}
function draw(){ctx.clearRect(0,0,1600,1000);ctx.fillStyle='white';ctx.fillRect(0,0,1600,1000);if(bg){ctx.save();ctx.globalAlpha=state.backgroundOpacity;const s=Math.min(1600/bg.width,1000/bg.height),w=bg.width*s,h=bg.height*s;ctx.drawImage(bg,(1600-w)/2,(1000-h)/2,w,h);ctx.restore()}if($('gridToggle').checked){ctx.strokeStyle='#e5e7eb';ctx.lineWidth=1;for(let x=0;x<1600;x+=20){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,1000);ctx.stroke()}for(let y=0;y<1000;y+=20){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(1600,y);ctx.stroke()}}state.lines.forEach(l=>{if(!visible(l.layer))return;ctx.save();ctx.strokeStyle=l.color;ctx.lineWidth=l.type==='measure'?2:4;if(l.type==='measure')ctx.setLineDash([9,5]);ctx.beginPath();ctx.moveTo(l.x1,l.y1);ctx.lineTo(l.x2,l.y2);ctx.stroke();if(l.type==='measure'){ctx.fillStyle='#111827';ctx.font='15px sans-serif';ctx.fillText((Math.hypot(l.x2-l.x1,l.y2-l.y1)/100).toFixed(2)+' m',(l.x1+l.x2)/2+6,(l.y1+l.y2)/2-6)}ctx.restore()});state.objects.forEach(o=>{if(!visible(o.layer))return;ctx.save();ctx.globalAlpha=o.opacity;if(o.image)warp(img(o.image,o.remote),o.quad,o.flipH,o.flipV);else{const c=centroid(o.quad),b=bbox(o.quad);ctx.translate(c.x,c.y);ctx.rotate(o.rotation*Math.PI/180);ctx.fillStyle=o.color;ctx.fillRect(-b.w/2,-b.h/2,b.w,b.h);ctx.strokeStyle='#111827';ctx.strokeRect(-b.w/2,-b.h/2,b.w,b.h);ctx.fillStyle='white';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`${Math.min(b.w,b.h)*.35}px sans-serif`;ctx.fillText(o.icon||'■',0,-3);ctx.font='12px sans-serif';ctx.fillText(o.name,0,b.h/2-12,b.w-8)}ctx.restore();if(o.id===state.selectedId)drawSelection(o)});if(drawing){ctx.save();ctx.strokeStyle='#0ea5e9';ctx.lineWidth=3;ctx.setLineDash([8,5]);ctx.beginPath();ctx.moveTo(drawing.x1,drawing.y1);ctx.lineTo(drawing.x2,drawing.y2);ctx.stroke();ctx.restore()}}
function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)/state.zoom,y:(e.clientY-r.top)/state.zoom}}
function at(p){for(let i=state.objects.length-1;i>=0;i--){const o=state.objects[i];if(visible(o.layer)&&pointIn(p.x,p.y,o.quad))return o}return null}
function handle(o,p){for(let i=0;i<4;i++)if(dist(o.quad[i],p)<15)return{kind:'corner',i};const c=centroid(o.quad),t={x:(o.quad[0].x+o.quad[1].x)/2,y:(o.quad[0].y+o.quad[1].y)/2},v={x:t.x-c.x,y:t.y-c.y},l=Math.hypot(v.x,v.y)||1,r={x:t.x+v.x/l*35,y:t.y+v.y/l*35};if(dist(r,p)<15)return{kind:'rotate',center:c};return null}
canvas.addEventListener('pointerdown',e=>{const p=point(e);if(state.tool==='line'||state.tool==='measure'){drawing={x1:p.x,y1:p.y,x2:p.x,y2:p.y,type:state.tool};canvas.setPointerCapture(e.pointerId);return}if(state.tool==='label'){const t=prompt('Label text:');if(t)addAsset({name:t,type:'text',w:220,h:55,color:'#111827'},p.x,p.y);return}const s=selected();if(s?.quad){const h=handle(s,p);if(h){push();drag={...h,start:p,orig:structuredClone(s.quad),center:h.center||centroid(s.quad),baseRotation:s.rotation};canvas.setPointerCapture(e.pointerId);return}}const o=at(p);state.selectedId=o?.id||null;if(o&&!locked(o.layer)){push();drag={kind:'move',start:p,orig:structuredClone(o.quad)};canvas.setPointerCapture(e.pointerId)}else if(state.tool==='pan'){drag={kind:'pan',sx:e.clientX,sy:e.clientY,sl:viewport.scrollLeft,st:viewport.scrollTop};canvas.setPointerCapture(e.pointerId)}renderAll()});
canvas.addEventListener('pointermove',e=>{const p=point(e);if(drawing){drawing.x2=p.x;drawing.y2=p.y;draw();return}if(!drag)return;if(drag.kind==='pan'){viewport.scrollLeft=drag.sl-(e.clientX-drag.sx);viewport.scrollTop=drag.st-(e.clientY-drag.sy);return}const o=selected();if(!o?.quad)return;if(drag.kind==='move'){let dx=p.x-drag.start.x,dy=p.y-drag.start.y;if($('snapToggle').checked){dx=snap(dx);dy=snap(dy)}o.quad=drag.orig.map(q=>({x:q.x+dx,y:q.y+dy}))}else if(drag.kind==='corner'){if(state.mode==='distort')o.quad[drag.i]=p;else{const oi=(drag.i+2)%4,fix=drag.orig[oi],oc=drag.orig[drag.i],sx=(p.x-fix.x)/(oc.x-fix.x||1),sy=(p.y-fix.y)/(oc.y-fix.y||1);o.quad=drag.orig.map(q=>({x:fix.x+(q.x-fix.x)*sx,y:fix.y+(q.y-fix.y)*sy}))}}else if(drag.kind==='rotate'){const a0=Math.atan2(drag.start.y-drag.center.y,drag.start.x-drag.center.x),a1=Math.atan2(p.y-drag.center.y,p.x-drag.center.x),deg=(a1-a0)*180/Math.PI;o.quad=rotate(drag.orig,deg,drag.center);o.rotation=drag.baseRotation+deg}renderAll()});
canvas.addEventListener('pointerup',e=>{if(drawing){const p=point(e);push();state.lines.push({id:uid(),type:drawing.type,name:drawing.type,x1:drawing.x1,y1:drawing.y1,x2:p.x,y2:p.y,color:drawing.type==='measure'?'#dc2626':'#111827',layer:drawing.type==='measure'?'measurements':'rigging'});drawing=null;renderAll()}drag=null});
canvas.addEventListener('dragover',e=>e.preventDefault());canvas.addEventListener('drop',e=>{e.preventDefault();const raw=e.dataTransfer.getData('application/x-simplerig');if(raw){const p=point(e);addAsset(JSON.parse(raw),p.x,p.y)}});
function renderInspector(){const o=selected();$('emptyInspector').hidden=!!o;$('inspector').hidden=!o;if(!o?.quad)return;const b=bbox(o.quad);$('objName').value=o.name;$('objWidth').value=Math.round(b.w);$('objHeight').value=Math.round(b.h);$('objRotation').value=Math.round(o.rotation||0);$('objOpacity').value=o.opacity;$('objNotes').value=o.notes||''}
function updateInspector(){const o=selected();if(!o?.quad)return;push();o.name=$('objName').value;o.opacity=+$('objOpacity').value;o.notes=$('objNotes').value;const b=bbox(o.quad),c=centroid(o.quad),w=Math.max(10,+$('objWidth').value),h=Math.max(10,+$('objHeight').value);o.quad=o.quad.map(p=>({x:c.x+(p.x-c.x)*w/(b.w||1),y:c.y+(p.y-c.y)*h/(b.h||1)}));const d=+$('objRotation').value-(o.rotation||0);o.quad=rotate(o.quad,d,c);o.rotation=+$('objRotation').value;renderAll()}
function renderLayers(){const el=$('layers');el.innerHTML='';state.layers.forEach(l=>{const d=document.createElement('div');d.className='layer-row';d.innerHTML=`<button data-v>${l.visible?'👁':'🚫'}</button><button data-l>${l.locked?'🔒':'🔓'}</button><span>${l.name}</span>`;d.querySelector('[data-v]').onclick=()=>{push();l.visible=!l.visible;renderAll()};d.querySelector('[data-l]').onclick=()=>{push();l.locked=!l.locked;renderAll()};el.appendChild(d)})}
function renderAll(){draw();renderInspector();renderLayers();renderCalendar();renderProjects()}
function del(){if(!state.selectedId)return;push();state.objects=state.objects.filter(o=>o.id!==state.selectedId);state.lines=state.lines.filter(l=>l.id!==state.selectedId);state.selectedId=null;renderAll()}function duplicate(){const o=selected();if(!o?.quad)return;push();const c=structuredClone(o);c.id=uid();c.name+=' Copy';c.quad=c.quad.map(p=>({x:p.x+30,y:p.y+30}));state.objects.push(c);state.selectedId=c.id;renderAll()}
function resetTransform(){const o=selected();if(!o?.quad)return;push();const c=centroid(o.quad),b=bbox(o.quad);o.quad=quad(c.x,c.y,b.w,b.h);o.rotation=0;o.flipH=o.flipV=false;renderAll()}
function exportPng(){state.selectedId=null;draw();try{canvas.toBlob(b=>b?download(b,(state.projectName||'SimpleRig')+'.png'):alert('Export blocked by a remote image. Download it and re-upload locally first.'))}catch{alert('Export blocked by a remote image. Download it and re-upload locally first.')}}function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
async function webSearch(){const key=$('googleKey').value.trim(),cx=$('googleCx').value.trim(),q=$('webQuery').value.trim();if(!key||!cx){$('searchStatus').textContent='Enter your API key and CX first.';return}if(!q)return;$('searchStatus').textContent='Searching…';$('webResults').innerHTML='';const p=new URLSearchParams({key,cx,q,searchType:'image',num:'10',safe:'active'});if($('webType').value)p.set('imgType',$('webType').value);if($('webFile').value)p.set('fileType',$('webFile').value);try{const r=await fetch('https://www.googleapis.com/customsearch/v1?'+p),d=await r.json();if(!r.ok)throw Error(d.error?.message||'Search failed');$('searchStatus').textContent=`${(d.items||[]).length} results`;for(const it of d.items||[]){const el=document.createElement('div');el.className='web-result';el.innerHTML=`<img src="${it.image?.thumbnailLink||it.link}" alt=""><p title="${it.title||''}">${it.title||'Image'}</p><button>Add to canvas</button>`;el.querySelector('button').onclick=()=>{addAsset({name:it.title||'Web image',type:'image',w:220,h:160,image:it.link,remote:true,sourcePage:it.image?.contextLink||''});$('searchStatus').textContent='Added. If it fails, download from the source page and import locally.'};$('webResults').appendChild(el)}}catch(e){$('searchStatus').textContent=e.message}}
function renderCalendar(){const el=$('calendarGrid');if(!el)return;el.innerHTML='';for(const d of ['Mon','Tue','Wed','Thu','Fri','Sat','Sun']){const h=document.createElement('div');h.className='calendar-head';h.textContent=d;el.appendChild(h)}const first=new Date(state.year,state.month,1),off=(first.getDay()+6)%7,start=new Date(state.year,state.month,1-off);$('calendarTitle').textContent=first.toLocaleString('en-GB',{month:'long',year:'numeric'});for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const key=d.toISOString().slice(0,10),cell=document.createElement('div');cell.className='calendar-day'+(d.getMonth()!==state.month?' other':'');cell.innerHTML=`<div class="day-num">${d.getDate()}</div>`;for(const t of state.calendar.filter(t=>t.date===key)){const card=document.createElement('div');card.className='task';card.draggable=true;card.textContent=`${t.type}: ${t.title}`;card.addEventListener('dragstart',e=>e.dataTransfer.setData('text/task',t.id));card.ondblclick=()=>{if(confirm('Delete this item?')){state.calendar=state.calendar.filter(x=>x.id!==t.id);push();renderCalendar()}};cell.appendChild(card)}cell.onclick=e=>{if(e.target!==cell&&!e.target.classList.contains('day-num'))return;pendingDate=key;$('taskModal').hidden=false};cell.ondragover=e=>e.preventDefault();cell.ondrop=e=>{e.preventDefault();const t=state.calendar.find(x=>x.id===e.dataTransfer.getData('text/task'));if(t){t.date=key;push();renderCalendar()}};el.appendChild(cell)}}
function calc(){const kg=Math.max(0,+$('calcLoad').value||0),r=Math.max(1,+$('calcRatio').value||1),e=clamp(+$('calcEfficiency').value||100,1,100)/100,d=Math.max(.1,+$('calcDisadvantage').value||1),n=Math.max(0,+$('calcRedirects').value||0),load=kg*9.81,ideal=load/r,actual=ideal/e*d;$('rLoad').textContent=load.toFixed(0)+' N';$('rIdeal').textContent=ideal.toFixed(0)+' N';$('rActual').textContent=actual.toFixed(0)+' N';$('rKg').textContent=(actual/9.81).toFixed(1)+' kgf';$('rTension').textContent=actual.toFixed(0)+' N';$('rRedirect').textContent=n?(actual*2).toFixed(0)+' N × '+n:'None';$('rTravel').textContent=r.toFixed(1)+' m';$('rFactor').textContent=(r*e/d).toFixed(2)+':1'}
function renderProjects(){const el=$('projectsGrid');if(!el)return;el.innerHTML='';for(const p of Object.values(projects()).sort((a,b)=>b.updated.localeCompare(a.updated))){const c=document.createElement('div');c.className='project-card';c.innerHTML=`<div class="project-thumb">S</div><h3>${p.name.replace(/[<>]/g,'')}</h3><p>Updated ${new Date(p.updated).toLocaleString('en-GB')}</p><div class="project-actions"><button data-o>Open</button><button data-d>Duplicate</button><button data-x>Delete</button></div>`;c.querySelector('[data-o]').onclick=()=>{Object.assign(state,JSON.parse(p.data));$('projectName').value=state.projectName;state.selectedId=null;loadBg();renderAll();switchView('workspace')};c.querySelector('[data-d]').onclick=()=>{const ps=projects(),d=JSON.parse(p.data),id=uid();d.projectId=id;d.projectName+=' Copy';ps[id]={id,name:d.projectName,updated:new Date().toISOString(),data:JSON.stringify(d)};localStorage.setItem('simplerig2d-projects',JSON.stringify(ps));renderProjects()};c.querySelector('[data-x]').onclick=()=>{if(confirm('Delete project?')){const ps=projects();delete ps[p.id];localStorage.setItem('simplerig2d-projects',JSON.stringify(ps));renderProjects()}};el.appendChild(c)}}
function switchView(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$(v+'View').classList.add('active');if(v==='calendar')renderCalendar();if(v==='projects')renderProjects()}function zoom(z){state.zoom=clamp(z,.25,2);canvas.style.transform=`scale(${state.zoom})`;canvas.style.marginRight=`${1600*(state.zoom-1)}px`;canvas.style.marginBottom=`${1000*(state.zoom-1)}px`;$('zoomLabel').textContent=Math.round(state.zoom*100)+'%'}
for(const b of document.querySelectorAll('.tab'))b.onclick=()=>switchView(b.dataset.view);for(const b of document.querySelectorAll('.tool'))b.onclick=()=>{document.querySelectorAll('.tool').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.tool=b.dataset.tool};for(const b of document.querySelectorAll('.mode'))b.onclick=()=>{document.querySelectorAll('.mode').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.mode=b.dataset.mode};
$('newBtn').onclick=$('createProject').onclick=()=>{if(confirm('Create a new project?')){Object.assign(state,{projectId:uid(),projectName:'Untitled Project',objects:[],lines:[],background:null,backgroundOpacity:.8,layers:structuredClone(defaultLayers),selectedId:null,history:[],future:[],calendar:[],customAssets:[]});$('projectName').value=state.projectName;loadBg();renderAll();save()}};$('saveBtn').onclick=save;$('projectName').oninput=push;$('exportProjectBtn').onclick=()=>download(new Blob([snapshot()],{type:'application/json'}),(state.projectName||'SimpleRig')+'.simplerig.json');$('importProject').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);d.projectId=uid();Object.assign(state,d);$('projectName').value=state.projectName;loadBg();renderAll();save()}catch{alert('Invalid project file')}};r.readAsText(f)};
$('deleteBtn').onclick=del;$('duplicateBtn').onclick=duplicate;$('flipH').onclick=()=>{const o=selected();if(o?.quad){push();o.flipH=!o.flipH;draw()}};$('flipV').onclick=()=>{const o=selected();if(o?.quad){push();o.flipV=!o.flipV;draw()}};$('resetTransform').onclick=resetTransform;$('zoomIn').onclick=()=>zoom(state.zoom+.1);$('zoomOut').onclick=()=>zoom(state.zoom-.1);$('fit').onclick=()=>zoom(Math.min((viewport.clientWidth-50)/1600,(viewport.clientHeight-50)/1000));$('undo').onclick=()=>{if(state.history.length){state.future.push(snapshot());Object.assign(state,JSON.parse(state.history.pop()));state.selectedId=null;loadBg();renderAll()}};$('redo').onclick=()=>{if(state.future.length){state.history.push(snapshot());Object.assign(state,JSON.parse(state.future.pop()));state.selectedId=null;loadBg();renderAll()}};$('pngExport').onclick=exportPng;
$('backgroundOpacity').oninput=e=>{state.backgroundOpacity=+e.target.value;push();draw()};$('backgroundInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{push();state.background=r.result;loadBg()};r.readAsDataURL(f)};$('clearBackground').onclick=()=>{push();state.background=null;loadBg()};$('assetSearch').oninput=e=>renderAssets(e.target.value);$('customAssetInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{const a={name:prompt('Asset name:',f.name.replace(/\.[^.]+$/,''))||'Custom asset',type:'image',w:220,h:160,image:r.result};state.customAssets.push(a);renderAssets();addAsset(a)};r.readAsDataURL(f)};
for(const id of ['objName','objWidth','objHeight','objRotation','objOpacity','objNotes'])$(id).onchange=updateInspector;$('webSearch').onclick=webSearch;$('webQuery').onkeydown=e=>{if(e.key==='Enter')webSearch()};$('saveGoogle').onclick=()=>{localStorage.setItem('simplerig-google-key',$('googleKey').value);localStorage.setItem('simplerig-google-cx',$('googleCx').value);$('searchStatus').textContent='Saved in this browser.'};$('googleKey').value=localStorage.getItem('simplerig-google-key')||'';$('googleCx').value=localStorage.getItem('simplerig-google-cx')||'';
$('prevMonth').onclick=()=>{if(--state.month<0){state.month=11;state.year--}renderCalendar()};$('nextMonth').onclick=()=>{if(++state.month>11){state.month=0;state.year++}renderCalendar()};$('saveTask').onclick=()=>{const t=$('taskTitle').value.trim();if(t){state.calendar.push({id:uid(),date:pendingDate,title:t,type:$('taskType').value});$('taskTitle').value='';$('taskModal').hidden=true;push();renderCalendar()}};$('cancelTask').onclick=()=>$('taskModal').hidden=true;for(const id of ['calcLoad','calcRatio','calcEfficiency','calcDisadvantage','calcRedirects'])$(id).oninput=calc;$('calculate').onclick=calc;
window.onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();save()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();$('undo').click()}if(e.key==='Delete'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName))del()};
const current=localStorage.getItem('simplerig2d-current'),ps=projects();if(current&&ps[current]){Object.assign(state,JSON.parse(ps[current].data));$('projectName').value=state.projectName;loadBg()}else save();renderAssets();zoom(1);renderAll();calc();
})();
